# Generated by Django 2.2.4 on 2019-08-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.PositiveIntegerField()),
                ('details_of_route', models.CharField(max_length=50)),
                ('time_from', models.TimeField(auto_now=True)),
                ('time_to', models.TimeField(auto_now=True)),
                ('return_date', models.DateField(auto_now=True)),
                ('number_of_personnel', models.PositiveSmallIntegerField()),
                ('directorate', models.CharField(choices=[('ED', 'ED'), ('DFA', 'DFA'), ('DNF', 'DNF')], max_length=10)),
                ('trans_officer', models.CharField(max_length=10, verbose_name='TO')),
            ],
        ),
    ]
